project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - text: About Me
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact Me
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css